name: Linter

on:
  merge_group:
  pull_request:

jobs:
  text-linter:
    name: TEXT linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create and use reduced-dependencies package.json
        run: |
          mkdir -p tmp
          jq '.devDependencies |= with_entries( select(.key | startswith("textlint")))
              | del(.dependencies, .optionalDependencies)' \
              package.json > tmp/package-ci.json
          cp tmp/package-ci.json package.json
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: tmp/package-ci.json
      - run: npm install --ignore-scripts --omit=optional
      - run: .github/workflows/scripts/textlint.sh

  markdown-linter:
    name: MARKDOWN linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create and use reduced-dependencies package.json
        run: |
          mkdir -p tmp
          jq '.devDependencies |= with_entries(
                  select(.key | test("gulp|markdown|through|require|yargs|js-yaml|ajv|ajv-formats|ajv-errors"))
                )
                | del(.dependencies, .optionalDependencies)' \
            package.json > tmp/package-ci.json
          cp tmp/package-ci.json package.json
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: tmp/package-ci.json
      - run: npm install --ignore-scripts --omit=optional
      - run: npm run check:markdown
      - name: Get list of changed non-en files
        id: changed-files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'content/[^e][^n]/**/*.md' || true)"
      - name: Run markdownlint-cli2 on changed files
        if: steps.changed-files.outputs.files != ''
        run: npx markdownlint-cli2 ${{ steps.changed-files.outputs.files }}
