name: PR actions

on:
  issue_comment:
    types: [created]

jobs:
  fix-format:
    name: /fix:format
    runs-on: ubuntu-latest
    if:
      ${{ github.event.issue.pull_request }} &&
      contains(github.event.comment.body, '/fix:format')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run prettier:write
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Results from /fix:format'
          commit_user_name: opentelemetrybot
          commit_user_email: 107717825+opentelemetrybot@users.noreply.github.com
        # env:
        #   GH_TOKEN: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}
